// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not modify it by hand because the contents might be overwritten
// from other tools (Swift Playgrounds / Xcode).

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Appunti",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Appunti",
            targets: ["AppModule"],
            bundleIdentifier: "it.cristina.appunti",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .pencil),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
